title: Cloud Egineer @ Nutrien Ag Solutions
author: ethanels
email: ethancol3.23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dedicated, passionate, learner. Looking for skills in Agile, Management
  Scrum, Diversity and a great edition to your corporate culture? 
  Resume for Ethan Elsbecker at Nutrien Ag Solutions
  
# social links
linkedin_username: ethan-elsbecker-b824b5199
github_username:  ethanels

show_excerpts: true # set to false to remove excerpts on the homepage
